name: gimp-edge
version: "2.9.5~git"
license: parts/gimp/build/src/LICENSE.txt
summary: GNU Image Manipulation Program - www.gimp.org
description: |
  A freely distributed program for such tasks as photo retouching, image
  composition and image authoring.  Whether you are a graphic designer,
  photographer, illustrator, or scientist, GIMP provides you with sophisticated
  tools to get your job done.  You can further enhance your productivity with
  GIMP thanks to many customization options and 3rd party plugins.
grade: devel
confinement: devmode

apps:
  gimp-edge:
    command: desktop-launch gimp
    plugs: [x11, unity7, opengl, home, gsettings]

parts:
  babl: 
    source: git://git.gnome.org/babl
    plugin: autotools
    configflags: [--disable-docs]
    install-via: prefix
    after: [libmypaint]
    build-packages:
      - autoconf
      - build-essential
      - dh-autoreconf
      - libgdk-pixbuf2.0-dev
  gegl:
    source: git://git.gnome.org/gegl
    plugin: autotools
    configflags: 
      - --enable-gtk-doc-html=no
      - --enable-workshop
    install-via: prefix
    build-packages:
      - autoconf
      - build-essential
      - dh-autoreconf
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libcairo2-dev
      - libexiv2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgexiv2-dev
      - libgraphviz-dev
      - libjasper-dev
      - libjpeg-dev
      - libjson-glib-dev
      - liblensfun-dev
      - liblua5.1-0-dev
      - libopenexr-dev
      - libpango1.0-dev
      - libpng12-dev
      - libraw-dev
      - librsvg2-dev
      - libsdl1.2-dev
      - libsdl2-dev
      - libspiro-dev
      - libtiff5-dev
      - libv4l-dev
      - libwebp-dev
      - lua5.1
      - python3-pydot
      - ruby
    after: [libmypaint, babl]
  gimp:
    source: git://git.gnome.org/gimp
    plugin: autotools
    configflags: 
      - --disable-gtk-doc
      - --disable-python
      - --disable-shared
      - --enable-vector-icons
    install-via: prefix
    build-packages:
      - autoconf-archive
      - build-essential
      - dh-translations
      - docbook
      - docbook-dsssl
      - docbook-to-man
      - docbook-xml
      - docbook-xsl
      - gir1.2-gudev-1.0
      - gir1.2-poppler-0.18
      - gnome-common
      - gnome-pkg-tools
      - gtk-doc-tools
      - jade
      - libaa1-dev
      - libamd2.4.1
      - libart-2.0-dev
      - libblas-common
      - libblas3
      - libbz2-dev
      - libcamd2.4.1
      - libccolamd2.9.1
      - libcdb-dev
      - libcholmod3.0.6
      - libcolamd2.9.1
      - libcups2-dev
      - libcupsfilters-dev
      - libcupsfilters1
      - libcupsimage2-dev
      - libcurl4-gnutls-dev
      - libdbus-glib-1-dev
      - libexif-dev
      - libffi-dev
      - libfontconfig1-dev
      - libgdk-pixbuf2.0-doc
      - libgfortran3
      - libgs-dev
      - libgs9
      - libgs9-common
      - libgtk2.0-dev
      - libgtk2.0-bin
      - libgtk2.0-doc
      - libgudev-1.0-dev
      - libidn11-dev
      - libijs-0.35
      - libijs-dev
      - libjbig2dec0
      - libjbig2dec0-dev
      - libjpeg-dev
      - liblapack3
      - libmng2
      - libmng-dev
      - libpango1.0-dev
      - libpaper-dev
      - libpaper1
      - libpng12-dev
      - libpoppler-dev
      - libpoppler-glib-dev
      - libpoppler-glib8
      - libpoppler58
      - libpython-dev
      - libpython2.7-dev
      - librsvg2-dev
      - libsp1c2
      - libsuitesparseconfig4.4.6
      - libtiff5-dev
      - libumfpack5.7.1
      - libwebkit-dev
      - libwmf-dev
      - libxmu-dev
      - libxmu-headers
      - libxpm-dev
      - patchutils
      - pkg-config
      - poppler-data
      - sgml-data
      - xsltproc
      - zlib1g-dev
    stage-packages:
      - gimp-gmic
    after: [babl, gegl, libmypaint] 
  libmypaint:
    source: git://github.com/mypaint/libmypaint.git
    plugin: autotools
    install-via: prefix
    build-packages:
      - build-essential
      - intltool
      - libjson-c-dev
      - liblcms2-dev
      - libpng12-dev
      - librsvg2-dev
      - python-gi
