name: shotwell
version: 0.23.5
summary: Shotwell photo manager
description: |
  Shotwell is a digital photo organizer designed for the GNOME desktop
  environment. It allows you to import photos from disk or camera, organize
  them in various ways, view them in full-window or fullscreen mode, and
  export them to share with others. It is able to manage a lot of different
  image formats, also including raw CR2 files.
confinement: strict

apps:
  shotwell:
    command: shotwell-launcher "$@"
    plugs: [x11, unity7, home, network]

parts:
  shotwell-launcher:
    source: .
    plugin: dump
    organize:
      shotwell-launcher: bin/shotwell-launcher
  shotwell:
    source: git://git.gnome.org/shotwell.git
    source-tag: shotwell-0.23.5
    plugin: autotools
    build-packages:
      - desktop-file-utils
      - gnome-doc-utils
      - libexif-dev
      - libgee-0.8-dev
      - libgexiv2-dev
      - libglib2.0-dev
      - libgphoto2-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - libraw-dev
      - librest-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libwebkit2gtk-4.0-dev
      - libxml2
      - m4
      - valac
      - libaccounts-glib-dev
      - libsignon-glib-dev
      - libunity-dev
      - python-scour
      - intltool
      - appstream-util
      - yelp-tools
    stage-packages:
      - libc6
      - libcairo2
      - libexif12
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgexiv2-2
      - libglib2.0-0
      - libgphoto2-6
      - libgphoto2-port12
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk-3-0
      - libgudev-1.0-0
      - libjson-glib-1.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libraw15
      - librest-0.7-0
      - libsoup2.4-1
      - libsqlite3-0
      - libunity9
      - libwebkit2gtk-4.0-37
      - libxml2
      - librsvg2-common
      - dbus-x11
      - dconf-tools
    after: [desktop-gtk3]
