name: qownnotes
version: "16.09.2"
summary: Plain-text file notepad with markdown support and ownCloud integration
confinement: strict
description: |
  QOwnNotes is the open source (GPL) plain-text file notepad with markdown support
  and todo list manager for GNU/Linux, Mac OS X and Windows, that (optionally) works
  together with the notes application of ownCloud.
  http://www.qownnotes.org/

apps:
  qownnotes:
    command: desktop-launch QOwnNotes --snap
    plugs:
      - x11
      - network
      - network-bind
      - home

parts:
  qownnotes:
    source: http://downloads.sourceforge.net/project/qownnotes/src/qownnotes-16.09.2.tar.xz
    plugin: qmake
    qt-version: qt5
    build-packages:
      - qttools5-dev
      - build-essential
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - libqt5xmlpatterns5-dev
    stage-packages:
      - libqt5gui5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5widgets5
      - libqt5qml5
      - libqt5svg5
      - libqt5network5
      - libqt5xml5
      - libqt5xmlpatterns5
      - libqt5printsupport5
      - libqt5declarative5
    stage:
      - -usr/share/pkgconfig
    after: [desktop-qt5]
    
