name: pitivi-edge
version: 1.x~git
summary: Pitivi is a truly unique video editor
description: |
    Pitivi respects your freedom and keeps getting better with
    each new release. It will never require licensing fees or use
    DRM to prevent you from using it whenever, wherever and however
    you like. Developed collaboratively by people from all around
    the world, its sole purpose is to be a fantastic video editor
    to empower people to express themselves through video. Like
    GStreamer and GES, Pitivi is distributed under LGPL.
confinement: devmode

apps:
  pitivi-edge:
    command: desktop-launch pitivi
    plugs:
      - home
      - opengl
      - pulseaudio
      - unity7

parts:
  desktop/gtk3:
    build-packages:
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
  pitivi-edge:
    source: git://git.gnome.org/pitivi
    plugin: autotools
    build-packages:
      - build-essential
      - automake
      - libtool
      - itstool
      - gtk-doc-tools
      - yelp-tools
      - gnome-common
      - gnome-doc-utils
      - yasm
      - flex
      - bison
      - libgirepository1.0-dev
      - python3-dev
      - python3-gi
      - python-gi-dev
      - python3-cairo-dev
      - libcairo2-dev
      - python3-gi-cairo
      - python3-matplotlib
      - python3-numpy
      - libgdk-pixbuf2.0-dev
      - libpulse-dev
      - libgtk-3-dev
      - libxml2-dev
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgstreamer1.0-0
      - libglu1-mesa-dev
    stage-packages:
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
    stage:
      - -usr/share/pkgconfig
    after: [desktop/gtk3]
