name: ubuntu-clock-app
version: "3.8.480"
summary: Ubuntu Clock app
description: The clock app for all Ubuntu devices
confinement: devmode

apps:
  ubuntu-clock-app:
    command: clock
    plugs: [unity7, opengl, network, network-bind]

parts:
  clock:
    source: lp:ubuntu-clock-app
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - ubuntu-touch-sounds
      - suru-icon-theme
      - qml-module-qttest
      - qml-module-qtsysteminfo
      - qml-module-qt-labs-settings
      - qtdeclarative5-u1db1.0
      - qtdeclarative5-qtmultimedia-plugin
      - qtdeclarative5-qtpositioning-plugin
      - qtdeclarative5-ubuntu-content1
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtdeclarative5-folderlistmodel-plugin
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - qml-module-qtsysteminfo
      - qtmir-desktop
      - mir-graphics-drivers-desktop
    snap:
      - -usr/share/doc
      - -usr/include
  environment:
    source: .
    plugin: dump
    organize:
      clock.wrapper: bin/clock
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
