name: moon-buggy
version: "1.0.51.11"
summary: Drive a car across the moon
description: |
   Moon-buggy is a simple character graphics game, where you drive some
   kind of car across the moon's surface.  Unfortunately there are
   dangerous craters there.  Fortunately your car can jump over them!
confinement: strict

apps:
  moon-buggy:
    command: bin/moon-buggy

parts:
  moon-buggy:
    source: https://github.com/sergiusens/moon-buggy.git
    plugin: autotools
    snap:
      - bin/moon-buggy
    build-packages:
      - libncurses5-dev
      - texinfo
